POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    
    "email" : "babos@banbo.fr" ,
    "password" : "hellohellohello"
   
}

###


POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    
    "email" : "babos@banbo.fr" ,
    "password" : "hellohellohello"
   
}